/**
 * Curated icon barrel.
 *
 * The project uses HugeIcons (`iconLibrary: "hugeicons"` in components.json).
 * Every name here is re-exported from `@hugeicons/core-free-icons` under a
 * stable, product-meaningful alias so feature code never has to guess an icon
 * name — a typo here is a build error, not a silently missing icon at runtime.
 */
export {
  AddCircleIcon,
  Alert02Icon,
  Analytics01Icon,
  AnalyticsUpIcon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUpRight01Icon as ExternalLinkIcon,
  Calendar01Icon,
  Cancel01Icon,
  CancelCircleIcon,
  ChartBarLineIcon,
  Chat01Icon,
  ChatAdd01Icon,
  CheckmarkCircle01Icon,
  Clock01Icon,
  Coins01Icon,
  Copy02Icon,
  DashboardSquare01Icon as DashboardIcon,
  Delete01Icon as TrashIcon,
  Download01Icon as DownloadIcon,
  Edit02Icon as PencilIcon,
  EyeIcon,
  File01Icon,
  FilterIcon,
  FlashIcon,
  Folder01Icon,
  GitCompareIcon as CompareIcon,
  HelpCircleIcon,
  Image01Icon,
  ImportIcon as ImportIcon,
  InformationCircleIcon,
  Layers01Icon,
  LayoutGridIcon,
  Link01Icon,
  LogoutSquare01Icon as LogoutIcon,
  MagicWand01Icon,
  Mail01Icon,
  Menu01Icon,
  Mic01Icon,
  MoneySend01Icon,
  Note01Icon,
  Notification01Icon as NotificationIcon,
  Pdf01Icon as PdfIcon,
  PencilEdit02Icon as EditIcon,
  PlayIcon,
  PlusSignIcon as PlusIcon,
  Presentation01Icon as PresentIcon,
  RefreshIcon as RetryIcon,
  Rocket01Icon,
  Search01Icon as SearchIcon,
  Settings01Icon,
  Share01Icon,
  ShuffleIcon,
  SparklesIcon,
  StarIcon,
  Tag01Icon,
  Target01Icon,
  Task01Icon,
  Tick02Icon as CheckIcon,
  Unlink01Icon as UnlinkIcon,
  Upload01Icon,
  User02Icon as UserIcon,
  ViewIcon,
  WandIcon,
  ZapIcon,
} from "@hugeicons/core-free-icons";
